---
title: "raster smoothing"
author: "Jordan Wingenroth"
date: "December 11, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(spatialEco)
library(tiff)
library(raster)
library(rgdal)
library(maps)

setwd("C:/Users/Jordan Wingenroth/Google Drive/Grad school/September 2017-/Sustainability & Society (ESPM 261)/Term project/Modeling")

raster <- raster("rastersum.TIF")

farmdata <- readOGR("farmdata.shp")

plot(raster, xlab = "longitude", ylab = "latitude", ncol = 1000, nrow = 1000)
map("world", add = TRUE )

raster_crop <- crop(raster, extend(extent(farmdata), .1))
raster_smooth <- raster.gaussian.smooth(raster_crop, sigma = 10, n = 51)

plot(raster_crop)
plot(farmdata, add = TRUE )
map.cities()

plot(raster_smooth/.003)
plot(farmdata, add = TRUE )


writeRaster(x = raster_smooth, filename = "smoothedfinal.tif")
writeRaster(x = raster_crop, filename = "cropfinal.tif")

table <- data.frame(Key = farmdata$Key, "Final estimate" = extract(raster_smooth, farmdata), "Raw value" = extract(raster_crop, farmdata))

write.csv(table, file = "table.csv")

```
$$
\begin{table}[ht]
\centering
\begin{tabular}{rllrr}
  \hline
 & Address & Key & Final.estimate & Raw.value \\ 
  \hline
1 & 1935 Bohemian Hwy, Occidental, CA, 95465 & OCC01 & 0.12 & 1.00 \\ 
  2 & 478 Noonan Ranch Ln, Larkfield-Wikiup, CA, 95403 & LKW01 & 0.47 & 4.00 \\ 
  3 & 4993 Occidental Rd, Santa Rosa, CA, 95401 & SRO01 & 0.56 & 5.00 \\ 
  4 & 198 Ely Rd N, Petaluma, CA, 94954 & PTL01 & 0.91 & 8.00 \\ 
  5 & 301 Steele Ln, Santa Rosa, CA, 95403 & SRO02 & 0.70 & 6.00 \\ 
  6 & 1422 Forestview Dr, Santa Rosa, CA, 95401 & SRO03 & 0.54 & 4.00 \\ 
  7 & 459 Sequoia Ln, Sebastopol, CA, 95472 & SBP01 & 0.36 & 3.00 \\ 
  8 & 8657 Lancaster Dr, Rohnert Park, CA, 94928 & ROH01 & 0.89 & 8.00 \\ 
  9 & 8511 Liman Way, Rohnert Park, CA, 94928 & ROH02 & 0.88 & 8.00 \\ 
  10 & 885 Wildwood Trail, Santa Rosa, CA, 95409 & SRO04 & 0.75 & 6.00 \\ 
  11 & 901 Adele Dr, Windsor, CA, 95492 & WND01 & 0.16 & 1.00 \\ 
  12 & 6177 Sonoma Hwy, Santa Rosa, CA, 95409 & SRO05 & 0.79 & 7.00 \\ 
  13 & 1225 Fulton Rd, Santa Rosa, CA, 95401 & SRO06 & 0.60 & 5.00 \\ 
  14 & 6024 Fredricks Rd, Sebastopol, CA, 95472 & SBP02 & 0.58 & 5.00 \\ 
  15 & 651 Airport Blvd, Santa Rosa, CA, 95407 & SRO07 & 0.43 & 4.00 \\ 
  16 & 245 Mountain View Ave, Santa Rosa, CA, & SRO08 & 0.82 & 7.00 \\ 
  17 & 7450 Bodega Ave, Sebastopol, CA, 95472 & SBP03 & 0.41 & 4.00 \\ 
  18 & 1764 Cooper Rd, Sebastopol, CA, 95472 & SBP04 & 0.57 & 5.00 \\ 
  19 & 1001 McNear Ave, Petaluma, CA, 94952 & PTL02 & 0.84 & 8.00 \\ 
  20 & 11871 Bodega Hwy, Sebastopol, CA, 95472 & SBP05 & 0.14 & 1.00 \\ 
  21 & 12295 Old Redwood Hwy, Healdsburg, CA, 95448 & HLD01 & 0.07 & 1.00 \\ 
  22 & 4588 Bodega Ave, Petaluma, CA, 94952 & PTL03 & 0.70 & 6.00 \\ 
  23 & 7905 Valentine Ave, Sebastopol, CA, 95472 & SBP06 & 0.36 & 3.00 \\ 
  24 & 1717 Yulupa Ave, Santa Rosa, CA, 95405 & SRO09 & 0.80 & 7.00 \\ 
  25 & 1632 West Ave, Santa Rosa, CA, 95407 & SRO10 & 0.77 & 7.00 \\ 
  26 & 55 Shasta Ave, Petaluma, CA, 94952 & PTL04 & 0.83 & 6.00 \\ 
  27 & 4250 Bones Rd, Sebastopol, CA, 95472 & SBP07 & 0.12 & 1.00 \\ 
  28 & 1425 Sunrise Parkway, Petaluma, CA, & PTL05 & 0.89 & 8.00 \\ 
  29 & 1075 Madrone Ave, Cotati, CA, 94931 & COT01 & 0.73 & 6.00 \\ 
   \hline
\end{tabular}
\end{table}
$$